context:
  version: "1.2.0"

package:
  name: libmd
  version: ${{ version }}

source:
  url: https://libbsd.freedesktop.org/releases/libmd-${{ version }}.tar.xz
  sha256: ac15ffb8430502fbaccdec66c5a82ee0eab0b0f36220df56710feadfeb13d0a0

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
  run_exports:
    - ${{ pin_subpackage('libmd') }}

tests:
  - script:
      - test -f ${PREFIX}/lib/libmd${SHLIB_EXT}

about:
  license: BSD-2-Clause
  license_file: COPYING
  summary: Message Digest functions from BSD systems
  homepage: https://www.hadrons.org/software/libmd/

extra:
  recipe-maintainers:
    - danielnachun
