context:
  version: 1.1.0

package:
  name: libmd
  version: ${{ version }}

source:
  url: https://libbsd.freedesktop.org/releases/libmd-${{ version }}.tar.xz
  sha256: 1bd6aa42275313af3141c7cf2e5b964e8b1fd488025caf2f971f43b00776b332

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
  run_exports:
    - ${{ pin_subpackage('libmd') }}

tests:
  - script:
      - test -f ${PREFIX}/lib/libmd${SHLIB_EXT}

about:
  license: BSD-2-Clause
  license_file: COPYING
  summary: Message Digest functions from BSD systems
  homepage: https://www.hadrons.org/software/libmd/

extra:
  recipe-maintainers:
    - danielnachun
